# Generated by Django 2.0.3 on 2018-04-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for the Analysis', primary_key=True, serialize=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('nodes', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=200)),
                ('o_stress', models.CharField(max_length=200)),
                ('o_strain', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Completed')], default='p', help_text='Analysis Status', max_length=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submission_date', 'status'],
            },
        ),
    ]
