# Generated by Django 2.0.3 on 2018-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nbm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='nodes',
            new_name='node',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Analysis Status', max_length=9),
        ),
    ]
