# Generated by Django 2.0.3 on 2018-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nbm', '0002_auto_20180405_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='element',
            new_name='co_ord',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='node',
            new_name='n_el_l',
        ),
        migrations.AddField(
            model_name='analysis',
            name='Analysis_type',
            field=models.CharField(blank=True, choices=[('b', 'buckle'), ('s', 'static')], default='s', help_text='Analysis Type', max_length=1),
        ),
        migrations.AddField(
            model_name='analysis',
            name='BC',
            field=models.CharField(blank=True, choices=[('p', 'pin'), ('f', 'fix')], default='p', help_text='Boundary Condition', max_length=1),
        ),
        migrations.AddField(
            model_name='analysis',
            name='El',
            field=models.IntegerField(default=29500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='Fy',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='Test_type',
            field=models.CharField(blank=True, choices=[('b', 'bend'), ('s', 'shear'), ('u', 'uniform')], default='s', help_text='Boundary Condition', max_length=1),
        ),
        migrations.AddField(
            model_name='analysis',
            name='depth',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='n_els',
            field=models.CharField(default='3 4 6 4 3', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='nu',
            field=models.IntegerField(default=0.3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Completed')], default='p', help_text='Analysis Status', max_length=1),
        ),
    ]
