# Generated by Django 2.0.3 on 2018-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nbm', '0004_auto_20180416_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='co_ord',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='n_el_l',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='n_els',
            field=models.TextField(max_length=20),
        ),
    ]
