# Generated by Django 2.0.3 on 2018-04-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nbm', '0005_auto_20180416_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='co_ord',
            field=models.TextField(max_length=50),
        ),
    ]
